apiVersion: v1
kind: Service
metadata:
  name: telegraf
  annotations:
    metallb.universe.tf/allow-shared-ip: default
spec:
  selector:
    app: telegraf
  type: ClusterIP
  ports:
    - name: telegraf
      port: 8185
      targetPort: 8185
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-deployment
  labels:
    app: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
      - name: telegraf
        image: telegraf_im
        imagePullPolicy: Never
        ports:
        - containerPort: 8185
          name: telegra