apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: metallb-config
data:
  config: |
    address-pools:
    - name: default
    protocole: layers2
    addresses:
    - 10.0.0.0-10.255.255.255