apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: default
spec:
  selector:
    app: ftps
  ports:
    - name: http
      protocol: TCP
      port: 21
      targetPort: 21
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_im
        imagePullPolicy: Never
        ports:
        - containerPort: 21
          name: http